/**
 * INSTACLARITY TEACHER APIS
 * INSTACLARITY TEACHER APIS
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;


import com.google.gson.annotations.SerializedName;

import java.io.Serializable;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


@ApiModel(description = "")
public class Teacher implements Serializable
{
	
	
	@SerializedName("specialization")
	private String specialization = null;
	
	@SerializedName("location")
	private String location = null;
	
	@SerializedName("experience")
	private Integer experience = null;

	/**
	 * specialization of teacher
	 **/
	@ApiModelProperty(value = "specialization of teacher")
	public String getSpecialization() 
	{
		return specialization;
	}
	public void setSpecialization(String specialization) 
	{
		this.specialization = specialization;
	}

	/**
	 * location of teacher
	 **/
	@ApiModelProperty(value = "location of teacher")
	public String getLocation() 
	{
		return location;
	}
	public void setLocation(String location) 
	{
		this.location = location;
	}

	/**
	 * experience of teaching in years
	 **/
	@ApiModelProperty(value = "experience of teaching in years")
	public Integer getExperience() 
	{
		return experience;
	}
	public void setExperience(Integer experience) 
	{
		this.experience = experience;
	}

	
	@Override
	public String toString(){
		StringBuilder sb = new StringBuilder();
		sb.append("class Teacher {\n");
		
		sb.append("specialization: ").append(specialization).append("\n");
		sb.append("location: ").append(location).append("\n");
		sb.append("experience: ").append(experience).append("\n");
		sb.append("}\n");
		return sb.toString();
	}
}
