/**
 * INSTACLARITY TEACHER APIS
 * INSTACLARITY TEACHER APIS
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;

import java.io.Serializable;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


@ApiModel(description = "")
public class User implements Serializable
{
	
	
	@SerializedName("email")
	private String email = null;
	
	@SerializedName("password")
	private String password = null;
	
	@SerializedName("full_name")
	private String fullName = null;
	
	@SerializedName("mobile_number")
	private String mobileNumber = null;
	
	@SerializedName("study_class")
	private Integer studyClass = null;
	
	@SerializedName("subject")
	private Integer subject = null;
	
	@SerializedName("token")
	private Token token = null;
	
	@SerializedName("teacher")
	private Teacher teacher = null;

	/**
	 * Email of the user.
	 **/
	@ApiModelProperty(value = "Email of the user.")
	public String getEmail() 
	{
		return email;
	}
	public void setEmail(String email) 
	{
		this.email = email;
	}

	/**
	 * Password of the user.
	 **/
	@ApiModelProperty(value = "Password of the user.")
	public String getPassword() 
	{
		return password;
	}
	public void setPassword(String password) 
	{
		this.password = password;
	}

	/**
	 * Full name of the user
	 **/
	@ApiModelProperty(value = "Full name of the user")
	public String getFullName() 
	{
		return fullName;
	}
	public void setFullName(String fullName) 
	{
		this.fullName = fullName;
	}

	/**
	 * MobileNum of the user.
	 **/
	@ApiModelProperty(value = "MobileNum of the user.")
	public String getMobileNumber() 
	{
		return mobileNumber;
	}
	public void setMobileNumber(String mobileNumber) 
	{
		this.mobileNumber = mobileNumber;
	}

	/**
	 * Study Class of User .
	 **/
	@ApiModelProperty(value = "Study Class of User .")
	public Integer getStudyClass() 
	{
		return studyClass;
	}
	public void setStudyClass(Integer studyClass) 
	{
		this.studyClass = studyClass;
	}

	/**
	 * Study Class of User .
	 **/
	@ApiModelProperty(value = "Study Class of User .")
	public Integer getSubject() 
	{
		return subject;
	}
	public void setSubject(Integer subject) 
	{
		this.subject = subject;
	}

	/**
	 **/
	@ApiModelProperty(value = "")
	public Token getToken() 
	{
		return token;
	}
	public void setToken(Token token) 
	{
		this.token = token;
	}

	/**
	 **/
	@ApiModelProperty(value = "")
	public Teacher getTeacher() 
	{
		return teacher;
	}
	public void setTeacher(Teacher teacher) 
	{
		this.teacher = teacher;
	}

	
	@Override
	public String toString(){
		StringBuilder sb = new StringBuilder();
		sb.append("class User {\n");
		
		sb.append("email: ").append(email).append("\n");
		sb.append("password: ").append(password).append("\n");
		sb.append("fullName: ").append(fullName).append("\n");
		sb.append("mobileNumber: ").append(mobileNumber).append("\n");
		sb.append("studyClass: ").append(studyClass).append("\n");
		sb.append("subject: ").append(subject).append("\n");
		sb.append("token: ").append(token).append("\n");
		sb.append("teacher: ").append(teacher).append("\n");
		sb.append("}\n");
		return sb.toString();
	}
}
